kanbaord-api:
    api-url: http://127.0.0.1/jsonrpc.php
    api-auth-token: 19ffd9709d03ce50675c3a43d1c49c1ac207f4bc45f06c5b2701fbdf8929
    api-header: X-API-Auth
    api-version: 2.0
    api-user: jsonrpc

kanbaord-setup:
    user:
        username: skylar
        password: skylar
        email: change.me@livingfire.local
        role: app-admin
    projects:
        - name: skylar
          description: skylar default project
          identifier: skylar
          swimlanes:
            - name: alert
            - name: todo
          columns:
            - title: backlog
              position: 1
            - title: new
              position: 2
            - title: in progress
              position: 3
            - title: complete
              position: 4
        - name: shopping
          description: skylar shopping
          identifier: shopping
          columns:
            - title: backlog
              position: 1
            - title: in progress
              position: 2
            - title: complete
              position: 3
          tasks:
            - title: eggs
              recurrence-trigger: 1
              recurrence-status: 1
            - title: milk
              recurrence-trigger: 1
              recurrence-status: 1
            - title: sugar
              recurrence-trigger: 1
              recurrence-status: 1
            - title: coffee
              recurrence-trigger: 1
              recurrence-status: 1
            - title: salt
              recurrence-trigger: 1
              recurrence-status: 1
          actions:
            - event-name: task.move.column
              action-name: \Kanboard\Action\TaskCloseColumn
              params:
                column_id: complete
